# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180709_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacenter',
            name='mod',
        ),
        migrations.RemoveField(
            model_name='datacenter',
            name='mod_type',
        ),
    ]
