# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-12 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180710_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacenter',
            name='scal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
